source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.3"

gem "rails", "~> 7.0.8", ">= 7.0.8.3"
gem "puma", "~> 5.0"
gem "pg", "~> 1.1"
gem "devise"
gem "devise_token_auth"
gem "kaminari"
gem "nokogiri"
gem "rack-cors"
gem "bootsnap", require: false
gem 'tzinfo-data', '~> 1.2023', '>= 1.2023.3'
# gem "localhost"

group :production do
  gem "rack-attack"    # リクエスト制限
  gem "oj"             # 高速なJSONパーサー
end

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
